### ISSUE TITLE
Refactor: use Promises for API communication

### ISSUE THREAD

**Issue by Solomonic** [crazyfactory/vue-product-description-manager#22]
Currently we are using JQueries `$.ajax` to send requests to `ajax_product_descriptor` and handle the callbacks in `product_descriptor.config.js`.

For issue #20 we already implemented  **Promise** based communication for one endpoint, now we want to replace the other existing endpoints to work the same way.

## Goal
- no  usage of `api.call()` anymore
- get rid off `product_descriptor.config.js`, all callbacks are now handled in app.js via Promises

## Endpoints ToDo
- [x] 'add_resource'
- [x] 'bulk_translation_complete'
- [x] 'delete_resource'
- [x] 'generate_description'
- [x] 'get_materials'
- [x] 'get_metatags'
- [x] 'get_baseproducts'
- [x] 'get_components'
- [x] 'get_products'
- [x] 'set_hidden_tag'
- [x] 'save_resource'
- [x] 'save_product'
- [x] 'save_products'
- [x] 'save_resources'
- [x] 'translation_update'
- [x] 'validate_translation_update'
- [x] 'update_translation_requested'
- [x] 'translation_complete'
- [x] 'get_translation_status' => remove it out

Create a **new branch** based on `'bulk_translation_complete'` and work the list of

**Comment by lalitaCF** [comment]
@Solomonic 
`get_translation_status`, in `ajax_product_descriptor` it is not used, I don't see where it is called.

So, Should we remove it out?

**Comment by Solomonic** [comment]
yes
