### ISSUE TITLE
Bug: Materials translations seem to disappear

### ISSUE THREAD

**Issue by Solomonic** [crazyfactory/vue-product-description-manager#35]
## Problem Description
Katharina from the Translators just reported the following issue.
All **materials** where already translated at least in
- DE
- EN-GB
- ES
- FR
- IT
- PT 
- RU 
- SV

Now it seems that a couple of them got the englisch default values back as seen in:

![screen shot 2561-01-25 at 1 54 43 pm](https://user-images.githubusercontent.com/3539915/35374927-8d738354-01d7-11e8-84e4-1c21dfc92ff4.png)
![screen shot 2561-01-25 at 1 55 01 pm](https://user-images.githubusercontent.com/3539915/35374930-8f84fbf0-01d7-11e8-827c-e8fae4406c67.png)
![screen shot 2561-01-25 at 1 55 44 pm](https://user-images.githubusercontent.com/3539915/35374931-91d006f2-01d7-11e8-8343-cd31c131ea99.png)

## Suspected Reasons
- Multiple translators work at the same time on the translations, are they overriding others?
- Materials where created twice, one was translated, the other one not

## Tasks
- investigate
- reproduce
- propose fix
- fix

**Comment by lalitaCF** [comment]
## Investigate
**In code: saveResource**
When we update and save resource, it will save in all language of the resource even we updated only a language.

**In live database: descriptor_log**
I saw 2 users updated materials between '2018-01-25 07:14:06' AND '2018-01-25 07:19:31'

![description_log](https://user-images.githubusercontent.com/8109587/35376276-e0d7681c-01dc-11e8-9ecc-3f45e1366e65.png)

**From logic saving in code and data in database,I think maybe translator updated same resource at the same time.**

**Comment by Solomonic** [comment]
bugfix merged to shop
