### ISSUE TITLE
Materials error tag doesn't make sense

### ISSUE THREAD

**Issue by lalitaCF** [crazyfactory/vue-product-description-manager#45]
## Problem
When some resources of materials was deleted. It also show the resources and show error tag `no materials`. So, admin have to reset resource before (choose '-' in selected box ) and add new resource. If admin forget reset them. It also keep deleted resources in materials.

![img_21022018_105332_0](https://user-images.githubusercontent.com/8109587/36826691-c4147f50-1d41-11e8-9337-03b82087b128.png)
  
So, I will propose solution follow this.

1. Show (x) icon in material column of rejected products table.
2. Add/ Repairs rejected product.
3. Remove deleted materials from product.
4. Validate product and show `* removed deleted materials`  in case which there are some materials was deleted.
5. User save product.
6. Product isn't in the table of rejected products.

**Comment by lalita13008** [comment]
## Solution
If some resources of materials was deleted, material will be reseted with `[]`. Admin have to set all material again :)

**Comment by lalitaCF** [comment]
[MR] https://gitlab.creations.de/crazy-factory/shop/merge_requests/1775

**Comment by lalitaCF** [comment]
More requirement

- [x] Resources in material look dirty even no any edit.
- [x] Set is_dirty = true when show 'Removed deleted materials'.
- [x] Make 'Removed deleted materials' more clear.
- [x] Add tooltip for describe what should to do of error tag.
- [x] Update MYSQL syntax with capitalization.
- [x] Return array in validateRejectedProduct().
- [x] investigate wrong order in resources of material
- [x] Show error tag when add product.
