### ISSUE TITLE
feat: force `en` and `de` languages for all products

### ISSUE THREAD

**Issue by turbo8p** [crazyfactory/vue-product-description-manager#68]
**Problem**
Since we introduce new shipping route and change the way how we declare things to customs.
Currently, ERP uses `de` and `en` as customs item description. If this information cannot be found, then the system cannot submit customs data. The orders that cannot be declared will get stuck in the collection center. We might notice these orders too late and make late delivery, unhappy customer.
![image](https://user-images.githubusercontent.com/26110220/50463112-202f8e80-09bc-11e9-8205-53720c3562b4.png)

**Solution**
- To ensure that we always have description of item, we need to force the user to fill in the first time they create the product.
- Please make `de` and `en` language in product descriptor as required fields. Don't allow user to by pass these two values.

**Comment by z3niths** [comment]
@CGundl 
We need to discuss with Product management
to clear about the requirement.

**Comment by z3niths** [comment]
@CGundl Dave will give you list @dacgray

**Comment by z3niths** [comment]
Moved to https://zube.io/crazyfactory/crazy-factory/c/6335
