### ISSUE TITLE
Product descriptor feature extension

### ISSUE THREAD

**Issue by z3niths** [crazyfactory/vue-product-description-manager#70]
![image.png](https://zube.io/files/crazyfactory/c94146ad5360a682b8fa6df8b46feec4-image.png)

At the moment the input element of the form were very small and hard to work with.

## Solution
Change from normal input to the button or clickable input element that's going to show a new popup with the text input field (Bigger space) and also explode() or replace the comma with linefeed. So it can show 
a tag/keyword per line. We also need a save button that gonna trim the input texts and implode them using comma as a delimiter

**Comment by z3niths** [comment]
Please make a PR to update this feature into the shop

**Comment by paibamboo** [comment]
Already merged to develop

**Comment by Shreepandey** [comment]
Looks good(edit delete,add,cancel,save)


![image.png](https://zube.io/files/crazyfactory/f4e4076160387ae270f20d2c33befccc-image.png)

**Comment by CGundl** [comment]
we have to show this feature to product management
once Anna clears the ticket we can move away from UAT

can u show her the new feature tomorrow @konthornR ?
